version: 0.2

env:
  variables:  
    TF_WORKING_DIR: "global/ci-cd/base-network"

phases:
  install: 
    commands: 
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -O /tmp/terraform.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform -version
    
  pre_build: 
    commands:
      - echo "Prepraing Directory Path.."
      - cd $TF_WORKING_DIR
      - ls -la

  build:
    commands:
      - echo "Applying saved plan..."
      - terraform init -input=false
      - terraform apply -input=false tfplan.binary

artifacts:
  files: []
