version: 0.2

env:
  variables:  
    TF_WORKING_DIR: "infrastructure/env/dev/base-network"
    PLAN_FILE: "tfplan.binary"

phases:
  install: 
    commands: 
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.4/terraform_1.13.4_linux_amd64.zip -O /tmp/terraform.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

    
  pre_build: 
    commands:
      - unset AWS_PROFILE || true
      - unset AWS_DEFAULT_PROFILE || true
      - export AWS_DEFAULT_REGION=ap-southeast-1
      - echo "Preparing working directory..."
      - ls -la $CODEBUILD_SRC_DIR/plan_output/infrastructure/env/dev/base-network
      - echo "Copying plan file into working directory"
      - cp $CODEBUILD_SRC_DIR/plan_output/infrastructure/env/dev/base-network/$PLAN_FILE $CODEBUILD_SRC_DIR/infrastructure/env/dev/base-network/$PLAN_FILE
      - cd $CODEBUILD_SRC_DIR/infrastructure/env/dev/base-network
      - ls -la
      - terraform init -input=false -reconfigure

  build:
    commands:
      - echo "Applying saved plan..."
      - terraform init -input=false
      - terraform apply -input=false tfplan.binary

artifacts:
  files: []
